# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.4.3"

gem "psych", "~> 4.0"
gem "prism" # loaded first in config/boot.rb on some Ruby builds where stdlib prism fails
gem "rails", "8.0.2"
gem "sqlite3", "~> 2.0"
gem "puma", ">= 6.0"
gem "rack-cors"
